#! /bin/sh

cp Multi-axisManipulatorSystem* /opt/Qt/apps -f
cp 3-5AxisRobotDatabase /opt/Qt/apps -f
cp -rf records resource stylesheet subs sysconfig Alarm.log /opt/Qt/apps
cp RunApp.sh /usr/bin -f
cp bcrypt /usr/bin -f
cp decrypt.sh /usr/bin -f
cp drivers/* /home/root -f
rm -r /Settings/sysconfig
cp 3a8.qmap /home/root -f
cp QtAutorun.sh /usr/bin -f
reboot
#cd 3a8
#cp -rf records subs sysconfig /mnt/database
#reboot
