#! /bin/sh

workDir=$1
binDir=$2
swVersion=$3

reinstallDir=${workDir}/${binDir}/Reinstall/Reinstall
contentDir=${workDir}/tools/Reinstall

rm -r ${workDir}/${binDir}/Reinstall
mkdir -p ${workDir}/${binDir}/Reinstall/Reinstall
#cp -r ${workDir}/tools/Reinstall/ ${workDir}/${binDir}/Reinstall
cp ${workDir}/${binDir}/Multi-axisManipulatorSystem ${reinstallDir} -f
cp ${workDir}/Multi-axisManipulatorSystem_ch.qm ${reinstallDir} -f
cp ${workDir}/Multi-axisManipulatorSystem_en.qm ${reinstallDir} -f

inch=`cat ${workDir}/Multi-axisManipulatorSystem.pro | grep "SK_SIZE =" | awk '{print $3}'`
#swVersion=`cat ${workDir}/config.h | grep "SW_VERSION " | awk '{print $3}' | sed 's/\"//g' | tr -d ['\r']`
#hwType=`cat ${workDir}/config.h | grep "HW_TYPE " | awk '{print $3}' | sed 's/\"//g' | tr -d ['\r']`
#swVersion=CYR${inch}_${hwType}_${swVersion}
cp ${contentDir}/${inch}-inch-qmap/3a8.qmap ${reinstallDir}
cp -r ${contentDir}/${inch}resource ${reinstallDir}/resourcee

cp -r ${contentDir}/${inch}records ${reinstallDir}/records

cp -r ${contentDir}/${inch}sysconfig ${reinstallDir}/sysconfig

cp -r ${contentDir}/${inch}inch-drivers ${reinstallDir}/drivers
cp -r ${contentDir}/stylesheet ${reinstallDir}/
cp -r ${contentDir}/subs ${reinstallDir}/
cp -f ${contentDir}/3-5AxisRobotDatabase ${reinstallDir}/
cp -f ${contentDir}/3a8HardwareTest-${inch}-inch ${reinstallDir}/3a8HardwareTest
cp -f ${contentDir}/*.qm ${reinstallDir}/
cp -f ${contentDir}/bcrypt ${reinstallDir}/
cp -f ${contentDir}/decrypt.sh ${reinstallDir}/
cp -f ${contentDir}/RunApp.sh ${reinstallDir}/
cp -f ${contentDir}/SelectSystemBootWay ${reinstallDir}/
cp -f ${contentDir}/update_cmd ${reinstallDir}/
cp -f ${contentDir}/UpdateGUI ${reinstallDir}/
echo "
#! /bin/sh
cd Reinstall
chmod +x ./SelectSystemBootWay
./SelectSystemBootWay -qws
" > ${workDir}/${binDir}/Reinstall/SelectSystemBootWay

chmod +x ${workDir}/${binDir}/Reinstall/SelectSystemBootWay

echo "
#! /bin/sh

cd drivers
chmod +x ./UpdateSystem.sh
./UpdateSystem.sh
cd ..
./UpdateGUI update_cmd -qws

reboot
" > ${workDir}/${binDir}/Reinstall/Reinstall/RobotFactorySettings.sh

chmod +x ${workDir}/bin/Reinstall/Reinstall/RobotFactorySettings.sh

echo "
#! /bin/sh

./3a8HardwareTest -qws 
" > ${workDir}/${binDir}/Reinstall/Reinstall/test_robot.sh

chmod +x ${workDir}/bin/Reinstall/Reinstall/test_robot.sh
echo "Create reinstall done!"

####### 创建更新包

echo ${swVersion}
updateDir=${workDir}/${binDir}/Update/HCRobotPanel${swVersion}
rm -r ${workDir}/${binDir}/Update
mkdir ${workDir}/${binDir}/Update
mkdir ${workDir}/${binDir}/Update/HCRobotPanel${swVersion}
cp -r ${workDir}/tools/Update/* ${workDir}/${binDir}/Update/HCRobotPanel${swVersion}
cp ${workDir}/${binDir}/Multi-axisManipulatorSystem ${updateDir} -f
cp ${workDir}/Multi-axisManipulatorSystem_ch.qm ${updateDir} -f
cp ${workDir}/Multi-axisManipulatorSystem_en.qm ${updateDir} -f

echo ${updateDir}.tar ${updateDir}
cd ${workDir}/${binDir}/Update/ && tar -cf HCRobotPanel${swVersion}.tar HCRobotPanel${swVersion}
HCbcrypt.sh ${updateDir}.tar

echo "Create update done!"
